name = "charlesgek-com"
compatibility_date = "2025-03-01"
main = "@astrojs/cloudflare/entrypoints/server"

[vars]
PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAAASAYgSU4eUBrEgL"
NODE_VERSION = "v24.21.0"

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "404-page"